// src/lib/components/particles/p-badge-19.tsx
"use client";

import { CheckIcon } from "lucide-react";
import { useId } from "react";
import { Badge } from "@/registry/default/ui/badge";
import { Checkbox } from "@/registry/default/ui/checkbox";

export default function Particle() {
  const id = useId();
  return (
    <Badge className="relative outline-none has-focus-visible:border-ring has-data-[state=unchecked]:bg-muted has-data-[state=unchecked]:text-muted-foreground has-focus-visible:ring-[3px] has-focus-visible:ring-ring/50">
      <Checkbox
        className="peer sr-only after:absolute after:inset-0"
        defaultChecked
        id={id}
      />
      <CheckIcon
        aria-hidden="true"
        className="hidden peer-data-[state=checked]:block"
      />
      <label
        className="cursor-pointer select-none after:absolute after:inset-0"
        htmlFor={id}
      >
        Selectable
      </label>
    </Badge>
  );
}

// src/lib/components/particles/badge/p-badge-19.svelte
<script lang="ts">
  import CheckIcon from '@lucide/svelte/icons/check';
  import { Badge } from '$lib/components/ui/badge';
  import { Checkbox } from '$lib/components/ui/checkbox';

  const id = $props.id();
</script>

<Badge
  class="relative outline-none has-focus-visible:border-ring has-data-unchecked:bg-muted has-data-unchecked:text-muted-foreground has-focus-visible:ring-[3px] has-focus-visible:ring-ring/50"
>
  <Checkbox class="peer hidden" checked {id} />
  <CheckIcon aria-hidden="true" class="hidden peer-data-[state=checked]:block" />
  <label class="cursor-pointer select-none after:absolute after:inset-0" for={id}>
    Selectable
  </label>
</Badge>
