// src/routes/demos/input-otp/+page.svelte
<script lang="ts">
    import ComponentPreviewTabs from "$lib/components/app/ComponentPreviewTabs.svelte";
    import {
        InputOTP,
        InputOTPGroup,
        InputOTPSeparator,
        InputOTPSlot,
    } from "$lib/components/ui/input-otp";
    import { Label } from "$lib/components/ui/label";

    let value = $state("");
    let invalid = $state(false);
    const id = "otp-input";

    const valid = $derived(value.length === 6 && value === "123456");
</script>

<ComponentPreviewTabs>
    <div class="flex flex-col items-center gap-2">
        <Label for={id}>Verification code</Label>
        <InputOTP
            aria-label="Verification code"
            {id}
            maxlength={6}
            bind:value
            onValueChange={(nextValue) => {
                invalid =
                    nextValue.length === 6 ? nextValue !== "123456" : false;
            }}
        >
            {#snippet children({ cells })}
                <InputOTPGroup>
                    <InputOTPSlot
                        aria-invalid={invalid || undefined}
                        cell={cells[0]}
                    />
                    <InputOTPSlot
                        aria-invalid={invalid || undefined}
                        cell={cells[1]}
                    />
                    <InputOTPSlot
                        aria-invalid={invalid || undefined}
                        cell={cells[2]}
                    />
                </InputOTPGroup>
                <InputOTPSeparator />
                <InputOTPGroup>
                    <InputOTPSlot
                        aria-invalid={invalid || undefined}
                        cell={cells[3]}
                    />
                    <InputOTPSlot
                        aria-invalid={invalid || undefined}
                        cell={cells[4]}
                    />
                    <InputOTPSlot
                        aria-invalid={invalid || undefined}
                        cell={cells[5]}
                    />
                </InputOTPGroup>
            {/snippet}
        </InputOTP>
        {#if !valid && !invalid}
            <p class="text-muted-foreground text-xs">
                Enter `123456` to pass validation.
            </p>
        {/if}
        {#if invalid}
            <p class="text-destructive-foreground text-xs">
                Code must be 123456.
            </p>
        {/if}
        {#if valid}
            <p class="text-success-foreground text-xs">Code verified.</p>
        {/if}
    </div>
</ComponentPreviewTabs>

// src/routes/demos/input-otp/page.tsx
"use client";

import { useId, useState } from "react";
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot,
} from "$lib/components/ui/input-otp";
import { Label } from "$lib/components/ui/label";

export default function Particle() {
  const id = useId();
  const [value, setValue] = useState("");
  const [invalid, setInvalid] = useState(false);
  const valid = value.length === 6 && value === "123456";

  return (
    <div className="flex flex-col items-center gap-2">
      <Label htmlFor={id}>Verification code</Label>
      <InputOTP
        aria-label="Verification code"
        id={id}
        maxLength={6}
        onChange={(nextValue) => {
          setValue(nextValue);
          setInvalid(nextValue.length === 6 ? nextValue !== "123456" : false);
        }}
        value={value}
      >
        <InputOTPGroup>
          <InputOTPSlot aria-invalid={invalid || undefined} index={0} />
          <InputOTPSlot aria-invalid={invalid || undefined} index={1} />
          <InputOTPSlot aria-invalid={invalid || undefined} index={2} />
          <InputOTPSlot aria-invalid={invalid || undefined} index={3} />
          <InputOTPSlot aria-invalid={invalid || undefined} index={4} />
          <InputOTPSlot aria-invalid={invalid || undefined} index={5} />
        </InputOTPGroup>
      </InputOTP>
      {!valid && !invalid && (
        <p className="text-muted-foreground text-xs">
          Enter `123456` to pass validation.
        </p>
      )}
      {invalid && (
        <p className="text-destructive-foreground text-xs">
          Code must be 123456.
        </p>
      )}
      {valid && (
        <p className="text-success-foreground text-xs">Code verified.</p>
      )}
    </div>
  );
}
