// src/lib/components/particles/p-otp-field-3.tsx
import {
  OTPField,
  OTPFieldInput,
  OTPFieldSeparator,
} from "@/registry/default/ui/otp-field";

const OTP_LENGTH = 6;
const GROUP_LENGTH = 3;

const OTP_SLOT_KEYS = Array.from(
  { length: OTP_LENGTH },
  (_, i) => `otp-slot-${i}`,
);

export default function Particle() {
  return (
    <OTPField aria-label="Verification code" length={OTP_LENGTH}>
      {OTP_SLOT_KEYS.slice(0, GROUP_LENGTH).map((slotKey, index) => (
        <OTPFieldInput
          key={slotKey}
          aria-label={`Character ${index + 1} of ${OTP_LENGTH}`}
        />
      ))}
      <OTPFieldSeparator />
      {OTP_SLOT_KEYS.slice(GROUP_LENGTH).map((slotKey, index) => (
        <OTPFieldInput
          key={slotKey}
          aria-label={`Character ${index + GROUP_LENGTH + 1} of ${OTP_LENGTH}`}
        />
      ))}
    </OTPField>
  );
}

// src/lib/components/particles/otp-field/p-otp-field-3.svelte
<script lang="ts">
  import {
    OTPField,
    OTPFieldInput,
    OTPFieldSeparator
  } from '#lib/components/ui/otp-field/index.js';

  const OTP_LENGTH = 6;
  const GROUP_LENGTH = 3;
</script>

<OTPField aria-label="Verification code" maxlength={OTP_LENGTH}>
  {#snippet children({ cells })}
    {#each cells.slice(0, GROUP_LENGTH) as cell, i (i)}
      <OTPFieldInput aria-label={`Character ${i + 1} of ${OTP_LENGTH}`} {cell} />
    {/each}
    <OTPFieldSeparator />
    {#each cells.slice(GROUP_LENGTH) as cell, i (i)}
      <OTPFieldInput aria-label={`Character ${i + GROUP_LENGTH + 1} of ${OTP_LENGTH}`} {cell} />
    {/each}
  {/snippet}
</OTPField>
