// src/routes/particles/page.tsx
import {
  PageHeader,
  PageHeaderDescription,
  PageHeaderHeading,
} from "@coss/ui/shared/page-header";
import type { Metadata } from "next";
import { Suspense } from "react";
import { isValidRegistryCategory } from "@/registry/registry-categories";
import { particles } from "@/registry/registry-particles";
import { ParticlesDisplay } from "./particles-display";
import SearchContainer from "./search-container";

const particleCount = particles.length;

const description = `Discover ${particleCount} ready-to-use particles, the building blocks of your design system. Filter by category to find the perfect component for your project.`;

export const metadata: Metadata = {
  description,
  title: "Browse Particles - coss ui",
};

async function ParticlesDisplayServer({
  searchParams,
}: {
  searchParams: Promise<{ tags?: string }>;
}) {
  const params = await searchParams;
  const rawCategories = params.tags?.split(",").filter(Boolean) || [];

  // Separate valid and invalid categories
  const validCategories = rawCategories.filter((category) =>
    isValidRegistryCategory(category),
  );
  const invalidCategories = rawCategories.filter(
    (category) => !isValidRegistryCategory(category),
  );

  // If there are invalid categories, show "no components found" message
  if (invalidCategories.length > 0) {
    return (
      <div className="text-center">
        <p className="text-muted-foreground">
          No particles found for the selected filters
        </p>
      </div>
    );
  }

  // If no valid categories, don't render anything
  if (validCategories.length === 0) return null;

  return <ParticlesDisplay selectedCategories={validCategories} />;
}

export default function Page({
  searchParams,
}: {
  searchParams: Promise<{ tags?: string }>;
}) {
  return (
    <div className="container w-full">
      <PageHeader className="*:pb-8!">
        <PageHeaderHeading>Browse Particles</PageHeaderHeading>
        <PageHeaderDescription className="max-w-2xl">
          {description}
        </PageHeaderDescription>
      </PageHeader>
      <Suspense>
        <SearchContainer />
      </Suspense>
      <Suspense>
        <ParticlesDisplayServer searchParams={searchParams} />
      </Suspense>
    </div>
  );
}

// src/routes/particles/+page.svelte
<script lang="ts">
	import { page } from "$app/state";
	import PageHeader from "$lib/components/shared-components/page-header.svelte";
	import PageHeaderHeading from "$lib/components/shared-components/page-header-heading.svelte";
	import PageHeaderDescription from "$lib/components/shared-components/page-header-description.svelte";
	import { particles } from "$lib/registry/registry-particles.js";
	import {
		isValidRegistryCategory,
		type RegistryCategory,
	} from "$lib/registry/registry-categories.js";
	import SearchContainer from "./SearchContainer.svelte";
	import ParticlesDisplay from "./ParticlesDisplay.svelte";

	const particleCount = particles.length;
	const description = `Discover ${particleCount} ready-to-use particles, the building blocks of your design system. Filter by category to find the perfect component for your project.`;

	const selectedCategories = $derived(() => {
		const rawCategories =
			page.url.searchParams.get("tags")?.split(",").filter(Boolean) ?? [];
		const validCategories = rawCategories.filter(
			isValidRegistryCategory,
		) as RegistryCategory[];

		const hasInvalid = rawCategories.some(
			(c) => !isValidRegistryCategory(c),
		);
		return { valid: validCategories, hasInvalid };
	});
</script>

<svelte:head>
	<title>Browse Particles - coss ui</title>
	<meta name="description" content={description} />
</svelte:head>

<div class="container w-full">
	<PageHeader class="*:pb-8!">
		<PageHeaderHeading>Browse Particles</PageHeaderHeading>
		<PageHeaderDescription class="max-w-2xl">
			{description}
		</PageHeaderDescription>
	</PageHeader>

	<SearchContainer />

	{#if selectedCategories().hasInvalid}
		<div class="text-center">
			<p class="text-muted-foreground">
				No particles found for the selected filters
			</p>
		</div>
	{:else if selectedCategories().valid.length > 0}
		<ParticlesDisplay selectedCategories={selectedCategories().valid} />
	{/if}
</div>
