// src/routes/particles/search-container.tsx
"use client";

import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useCallback, useMemo, useTransition } from "react";
import { Index } from "@/registry/__index__";
import { getCategorySortOrder } from "@/registry/registry-categories";
import SearchField from "./search-field";

const particles = Object.values(Index).filter(
  (item) => item.type === "registry:block",
);

const uniqueCategories = Array.from(
  new Set(particles.flatMap((particle) => particle.categories || [])),
).sort((a, b) => getCategorySortOrder(a) - getCategorySortOrder(b));

const searchItems = uniqueCategories.map((category) => ({
  label: category
    .split(" ")
    .map((word: string) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" "),
  value: category,
}));

export default function SearchContainer() {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  const [, startTransition] = useTransition();

  const selectedItems = useMemo(() => {
    const tags = searchParams?.get("tags")?.split(",").filter(Boolean) || [];
    return tags
      .map((tag) => searchItems.find((item) => item.value === tag))
      .filter((item): item is { label: string; value: string } => !!item);
  }, [searchParams]);

  const updateSelectedItems = useCallback(
    (items: { label: string; value: string }[]) => {
      startTransition(() => {
        const tags =
          items.length > 0 ? items.map((item) => item.value).join(",") : "";
        const newUrl = tags
          ? `${pathname}?tags=${encodeURIComponent(tags)}`
          : pathname;
        router.push(newUrl, { scroll: false });
      });
    },
    [router, pathname],
  );

  return (
    <div className="mb-8 md:mb-12 lg:mb-16">
      <SearchField
        items={searchItems}
        onItemsChange={updateSelectedItems}
        selectedItems={selectedItems}
      />
    </div>
  );
}

// src/routes/particles/search-container.svelte
<script lang="ts">
	import { getCategorySortOrder } from "$lib/registry/registry-categories";
	import { allParticles } from "$lib/registry/registry-particles";
	import SearchField, { type SearchItem } from "./search-field.svelte";
	import { browser } from "$app/environment";
	import { goto } from "$app/navigation";
	import { page } from "$app/state";

	const uniqueCategories = Array.from(
		// new Set(particles.flatMap((p) => p.categories ?? [])),
		new Set(Object.values(allParticles).flatMap((p) => p.tags)),
	).sort((a, b) => getCategorySortOrder(a) - getCategorySortOrder(b));

	const searchItems: SearchItem[] = uniqueCategories.map((category) => ({
		label: category
			.split(" ")
			.map((word) => word.charAt(0).toUpperCase() + word.slice(1))
			.join(" "),
		value: category,
	}));

	const selectedItems = $derived(
		(
			(browser ? page.url.searchParams.get("tags") : null)
				?.split(",")
				.filter(Boolean) ?? []
		)
			.map((tag) => searchItems.find((item) => item.value === tag))
			.filter((item): item is SearchItem => !!item),
	);

	function updateSelectedItems(items: SearchItem[]) {
		const tags =
			items.length > 0 ? items.map((i) => i.value).join(",") : "";
		const newUrl = tags
			? `${page.url.pathname}?tags=${encodeURIComponent(tags)}`
			: page.url.pathname;
		goto(newUrl, { noScroll: true });
	}
</script>

<div class="mb-8 md:mb-12 lg:mb-16">
	<SearchField
		items={searchItems}
		{selectedItems}
		onItemsChange={updateSelectedItems}
	/>
</div>
