// src/lib/components/particles/calendar/p-calendar-21.svelte
<script lang="ts">
  import {
    type DateValue,
    endOfMonth,
    endOfYear,
    getLocalTimeZone,
    startOfMonth,
    startOfYear,
    today,
  } from "@internationalized/date";
  import { Button } from "$lib/components/ui/button";
  import { RangeCalendar } from "$lib/components/ui/range-calendar";

  const todayValue = today(getLocalTimeZone());
  const yesterday = {
    end: todayValue.subtract({ days: 1 }),
    start: todayValue.subtract({ days: 1 }),
  };
  const last7Days = { end: todayValue, start: todayValue.subtract({ days: 6 }) };
  const last30Days = { end: todayValue, start: todayValue.subtract({ days: 29 }) };
  const monthToDate = { end: todayValue, start: startOfMonth(todayValue) };
  const lastMonthValue = todayValue.subtract({ months: 1 });
  const lastMonth = { end: endOfMonth(lastMonthValue), start: startOfMonth(lastMonthValue) };
  const yearToDate = { end: todayValue, start: startOfYear(todayValue) };
  const lastYearValue = todayValue.subtract({ years: 1 });
  const lastYear = { end: endOfYear(lastYearValue), start: startOfYear(lastYearValue) };

  let placeholder = $state<DateValue>(todayValue);
  let date = $state<{ end: DateValue | undefined; start: DateValue | undefined } | undefined>(last7Days);

  function isDateDisabled(d: DateValue): boolean {
    return d.compare(todayValue) > 0;
  }
</script>

<div class="flex max-sm:flex-col">
  <div class="relative py-1 ps-1 max-sm:order-1 max-sm:border-t">
    <div class="flex h-full flex-col sm:border-e sm:pe-3">
      <Button
        class="w-full justify-start"
        onclick={() => {
          date = { end: todayValue, start: todayValue };
          placeholder = todayValue;
        }}
        size="sm"
        variant="ghost"
      >
        Today
      </Button>
      <Button
        class="w-full justify-start"
        onclick={() => {
          date = yesterday;
          placeholder = yesterday.end;
        }}
        size="sm"
        variant="ghost"
      >
        Yesterday
      </Button>
      <Button
        class="w-full justify-start"
        onclick={() => {
          date = last7Days;
          placeholder = last7Days.end;
        }}
        size="sm"
        variant="ghost"
      >
        Last 7 days
      </Button>
      <Button
        class="w-full justify-start"
        onclick={() => {
          date = last30Days;
          placeholder = last30Days.end;
        }}
        size="sm"
        variant="ghost"
      >
        Last 30 days
      </Button>
      <Button
        class="w-full justify-start"
        onclick={() => {
          date = monthToDate;
          placeholder = monthToDate.end;
        }}
        size="sm"
        variant="ghost"
      >
        Month to date
      </Button>
      <Button
        class="w-full justify-start"
        onclick={() => {
          date = lastMonth;
          placeholder = lastMonth.end;
        }}
        size="sm"
        variant="ghost"
      >
        Last month
      </Button>
      <Button
        class="w-full justify-start"
        onclick={() => {
          date = yearToDate;
          placeholder = yearToDate.end;
        }}
        size="sm"
        variant="ghost"
      >
        Year to date
      </Button>
      <Button
        class="w-full justify-start"
        onclick={() => {
          date = lastYear;
          placeholder = lastYear.end;
        }}
        size="sm"
        variant="ghost"
      >
        Last year
      </Button>
    </div>
  </div>
  <RangeCalendar
    bind:placeholder
    class="max-sm:pb-3 sm:ps-5"
    {isDateDisabled}
    onValueChange={(newDate) => {
      if (newDate) date = newDate;
    }}
    value={date}
  />
</div>

// src/lib/components/particles/p-calendar-21.tsx
"use client";

import {
  endOfMonth,
  endOfYear,
  startOfMonth,
  startOfYear,
  subDays,
  subMonths,
  subYears,
} from "date-fns";
import { useState } from "react";
import type { DateRange } from "react-day-picker";
import { Button } from "@/registry/default/ui/button";
import { Calendar } from "@/registry/default/ui/calendar";

export default function Particle() {
  const today = new Date();
  const yesterday = {
    from: subDays(today, 1),
    to: subDays(today, 1),
  };
  const last7Days = {
    from: subDays(today, 6),
    to: today,
  };
  const last30Days = {
    from: subDays(today, 29),
    to: today,
  };
  const monthToDate = {
    from: startOfMonth(today),
    to: today,
  };
  const lastMonth = {
    from: startOfMonth(subMonths(today, 1)),
    to: endOfMonth(subMonths(today, 1)),
  };
  const yearToDate = {
    from: startOfYear(today),
    to: today,
  };
  const lastYear = {
    from: startOfYear(subYears(today, 1)),
    to: endOfYear(subYears(today, 1)),
  };
  const [month, setMonth] = useState(today);
  const [date, setDate] = useState<DateRange | undefined>(last7Days);

  return (
    <div className="flex max-sm:flex-col">
      <div className="relative py-1 ps-1 max-sm:order-1 max-sm:border-t">
        <div className="flex h-full flex-col sm:border-e sm:pe-3">
          <Button
            className="w-full justify-start"
            onClick={() => {
              setDate({
                from: today,
                to: today,
              });
              setMonth(today);
            }}
            size="sm"
            variant="ghost"
          >
            Today
          </Button>
          <Button
            className="w-full justify-start"
            onClick={() => {
              setDate(yesterday);
              setMonth(yesterday.to);
            }}
            size="sm"
            variant="ghost"
          >
            Yesterday
          </Button>
          <Button
            className="w-full justify-start"
            onClick={() => {
              setDate(last7Days);
              setMonth(last7Days.to);
            }}
            size="sm"
            variant="ghost"
          >
            Last 7 days
          </Button>
          <Button
            className="w-full justify-start"
            onClick={() => {
              setDate(last30Days);
              setMonth(last30Days.to);
            }}
            size="sm"
            variant="ghost"
          >
            Last 30 days
          </Button>
          <Button
            className="w-full justify-start"
            onClick={() => {
              setDate(monthToDate);
              setMonth(monthToDate.to);
            }}
            size="sm"
            variant="ghost"
          >
            Month to date
          </Button>
          <Button
            className="w-full justify-start"
            onClick={() => {
              setDate(lastMonth);
              setMonth(lastMonth.to);
            }}
            size="sm"
            variant="ghost"
          >
            Last month
          </Button>
          <Button
            className="w-full justify-start"
            onClick={() => {
              setDate(yearToDate);
              setMonth(yearToDate.to);
            }}
            size="sm"
            variant="ghost"
          >
            Year to date
          </Button>
          <Button
            className="w-full justify-start"
            onClick={() => {
              setDate(lastYear);
              setMonth(lastYear.to);
            }}
            size="sm"
            variant="ghost"
          >
            Last year
          </Button>
        </div>
      </div>
      <Calendar
        className="max-sm:pb-3 sm:ps-5"
        disabled={[{ after: today }]}
        mode="range"
        month={month}
        onMonthChange={setMonth}
        onSelect={(newDate) => {
          if (newDate) {
            setDate(newDate);
          }
        }}
        selected={date}
      />
    </div>
  );
}
