// src/lib/components/particles/calendar/p-calendar-19.svelte
<script lang="ts">
  import { DateFormatter, type DateValue, getLocalTimeZone, today } from '@internationalized/date';
  import { Calendar } from '$lib/components/ui/calendar';
  import { ScrollArea } from '$lib/components/ui/scroll-area';
  import { ToggleGroup, ToggleGroupItem } from '$lib/components/ui/toggle-group';

  const todayValue = today(getLocalTimeZone());
  let date = $state<DateValue>(todayValue);
  let time = $state<string | undefined>(undefined);

  const timeSlots = [
    { available: false, time: '09:00' },
    { available: false, time: '09:30' },
    { available: true, time: '10:00' },
    { available: true, time: '10:30' },
    { available: true, time: '11:00' },
    { available: true, time: '11:30' },
    { available: false, time: '12:00' },
    { available: true, time: '12:30' },
    { available: true, time: '13:00' },
    { available: true, time: '13:30' },
    { available: true, time: '14:00' },
    { available: false, time: '14:30' },
    { available: false, time: '15:00' },
    { available: true, time: '15:30' },
    { available: true, time: '16:00' },
    { available: true, time: '16:30' },
    { available: true, time: '17:00' },
    { available: true, time: '17:30' }
  ];

  const dayFormatter = new DateFormatter('en-US', { day: 'numeric', weekday: 'long' });

  function isDateDisabled(d: DateValue): boolean {
    return d.compare(todayValue) < 0;
  }
</script>

<div class="flex max-sm:flex-col">
  <Calendar
    bind:value={date}
    class="max-sm:pb-3 sm:pe-5"
    {isDateDisabled}
    onValueChange={(newDate) => {
      if (newDate) {
        time = undefined;
      }
    }}
    mode="single"
  />
  <div class="relative w-full max-sm:h-48 sm:w-40">
    <div class="absolute inset-0 max-sm:border-t">
      <ScrollArea class="h-full sm:border-s" scrollbarGutter scrollFade>
        <div class="flex flex-col gap-3 py-3 sm:pt-0 sm:pb-2">
          <div class="flex shrink-0 items-center font-medium text-sm sm:h-8 sm:px-5">
            {dayFormatter.format(date.toDate(getLocalTimeZone()))}
          </div>
          <ToggleGroup bind:value={time} class="grid w-full gap-1.5 max-sm:grid-cols-2 sm:px-5">
            {#each timeSlots as { time: timeSlot, available } (timeSlot)}
              <ToggleGroupItem disabled={!available} size="sm" value={timeSlot} variant="outline">
                {timeSlot}
              </ToggleGroupItem>
            {/each}
          </ToggleGroup>
        </div>
      </ScrollArea>
    </div>
  </div>
</div>

// src/lib/components/particles/p-calendar-19.tsx
"use client";

import { format } from "date-fns";
import { useState } from "react";
import { Calendar } from "@/registry/default/ui/calendar";
import { ScrollArea } from "@/registry/default/ui/scroll-area";
import { Toggle } from "@/registry/default/ui/toggle";
import { ToggleGroup } from "@/registry/default/ui/toggle-group";

export default function Particle() {
  const today = new Date();
  const [date, setDate] = useState<Date>(today);
  const [time, setTime] = useState<string | null>(null);

  const timeSlots = [
    { available: false, time: "09:00" },
    { available: false, time: "09:30" },
    { available: true, time: "10:00" },
    { available: true, time: "10:30" },
    { available: true, time: "11:00" },
    { available: true, time: "11:30" },
    { available: false, time: "12:00" },
    { available: true, time: "12:30" },
    { available: true, time: "13:00" },
    { available: true, time: "13:30" },
    { available: true, time: "14:00" },
    { available: false, time: "14:30" },
    { available: false, time: "15:00" },
    { available: true, time: "15:30" },
    { available: true, time: "16:00" },
    { available: true, time: "16:30" },
    { available: true, time: "17:00" },
    { available: true, time: "17:30" },
  ];

  return (
    <div className="flex max-sm:flex-col">
      <Calendar
        className="max-sm:pb-3 sm:pe-5"
        disabled={[{ before: today }]}
        mode="single"
        onSelect={(newDate) => {
          if (newDate) {
            setDate(newDate);
            setTime(null);
          }
        }}
        selected={date}
      />
      <div className="relative w-full max-sm:h-48 sm:w-40">
        <div className="absolute inset-0 max-sm:border-t">
          <ScrollArea className="h-full sm:border-s" scrollbarGutter scrollFade>
            <div className="flex flex-col gap-3 py-3 sm:pt-0 sm:pb-2">
              <div className="flex shrink-0 items-center font-medium text-sm sm:h-8 sm:px-5">
                {format(date, "EEEE, d")}
              </div>
              <ToggleGroup
                className="grid w-full gap-1.5 max-sm:grid-cols-2 sm:px-5"
                onValueChange={(values) => setTime(values[0] || null)}
                value={time ? [time] : []}
              >
                {timeSlots.map(({ time: timeSlot, available }) => (
                  <Toggle
                    disabled={!available}
                    key={timeSlot}
                    size="sm"
                    value={timeSlot}
                    variant="outline"
                  >
                    {timeSlot}
                  </Toggle>
                ))}
              </ToggleGroup>
            </div>
          </ScrollArea>
        </div>
      </div>
    </div>
  );
}
