// src/lib/components/particles/otp-field/p-otp-field-2.svelte
<script lang="ts">
  import { OTPField, OTPFieldInput } from '#lib/components/ui/otp-field/index.js';

  const OTP_LENGTH = 4;
</script>

<OTPField aria-label="One-time password" maxlength={OTP_LENGTH} size="lg">
  {#snippet children({ cells })}
    {#each cells as cell, i (i)}
      <OTPFieldInput aria-label={`Character ${i + 1} of ${OTP_LENGTH}`} {cell} />
    {/each}
  {/snippet}
</OTPField>

// src/lib/components/particles/p-otp-field-2.tsx
import { OTPField, OTPFieldInput } from "@/registry/default/ui/otp-field";

const OTP_LENGTH = 4;

const OTP_SLOT_KEYS = Array.from(
  { length: OTP_LENGTH },
  (_, i) => `otp-slot-${i}`,
);

export default function Particle() {
  return (
    <OTPField aria-label="One-time password" length={OTP_LENGTH} size="lg">
      {OTP_SLOT_KEYS.map((slotKey, index) => (
        <OTPFieldInput
          key={slotKey}
          aria-label={`Character ${index + 1} of ${OTP_LENGTH}`}
        />
      ))}
    </OTPField>
  );
}
