// src/lib/components/shared-components/mode-switcher.svelte
<script lang="ts">
  import { getContext } from "svelte";
  import { SunMoon } from "lucide-svelte";
  import { Button } from "$lib/components/ui/button";
  import {
    THEME_CONTEXT_KEY,
    type ThemeContextType,
  } from "./theme-provider.svelte";

  const themeCtx = getContext<ThemeContextType | undefined>(THEME_CONTEXT_KEY);

  function toggleTheme() {
    if (themeCtx) {
      themeCtx.setTheme(themeCtx.resolvedTheme === "dark" ? "light" : "dark");
    } else if (typeof document !== "undefined") {
      // Fallback: toggle dark class directly
      const isDark = document.documentElement.classList.toggle("dark");
      document.documentElement.style.colorScheme = isDark ? "dark" : "light";
    }
  }
</script>

<Button
  class="relative size-8"
  onclick={toggleTheme}
  size="icon"
  title="Toggle theme"
  variant="ghost"
>
  <SunMoon class="-rotate-45 size-4" strokeWidth={2} />
  <span class="sr-only">Toggle theme</span>
</Button>

// src/lib/shared-components/mode-switcher.tsx
"use client";

import { Button } from "@coss/ui/components/button";
import { LayerMask01Icon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { useTheme } from "next-themes";
import * as React from "react";

export function ModeSwitcher() {
  const { setTheme, resolvedTheme } = useTheme();

  const toggleTheme = React.useCallback(() => {
    setTheme(resolvedTheme === "dark" ? "light" : "dark");
  }, [resolvedTheme, setTheme]);

  return (
    <Button
      className="relative size-8"
      onClick={toggleTheme}
      size="icon"
      title="Toggle theme"
      variant="ghost"
    >
      <HugeiconsIcon
        className="-rotate-45 size-4"
        icon={LayerMask01Icon}
        strokeWidth={2}
      />
      <span className="sr-only">Toggle theme</span>
    </Button>
  );
}
