// src/lib/shared-components/products-dropdown.tsx
"use client";

import { Badge } from "@coss/ui/components/badge";
import { Button } from "@coss/ui/components/button";
import {
  Menu,
  MenuItem,
  MenuPopup,
  MenuTrigger,
} from "@coss/ui/components/menu";
import { ChevronDown } from "lucide-react";
import Link from "next/link";

interface ProductsDropdownProps {
  items: { href: string; label: string; upcoming?: boolean }[];
}

export function ProductsDropdown({ items }: ProductsDropdownProps) {
  const gatewayOrigin = process.env.NEXT_PUBLIC_COSS_URL || "";
  const uiGatewayOrigin = process.env.NEXT_PUBLIC_COSS_UI_URL || "";

  const getLinkProps = (item: {
    href: string;
    label: string;
    upcoming?: boolean;
  }) => {
    const isHomePage = item.href === "/";

    // Determine if this should be an external link and construct the URL
    if (gatewayOrigin && !isHomePage) {
      // Non-homepage links go to the main gateway
      return {
        href: `${gatewayOrigin}${item.href}`,
        isExternal: true,
      };
    }

    if (uiGatewayOrigin && isHomePage) {
      // Homepage links go to the UI gateway
      return {
        href: uiGatewayOrigin,
        isExternal: true,
      };
    }

    // Default: internal link
    return {
      href: item.href,
      isExternal: false,
    };
  };

  return (
    <Menu>
      <MenuTrigger render={<Button variant="ghost" />}>
        Products
        <ChevronDown />
      </MenuTrigger>
      <MenuPopup align="center" sideOffset={4}>
        {items.map((item) => {
          const { href, isExternal } = getLinkProps(item);

          return (
            <MenuItem
              className="group justify-between"
              key={item.href}
              // biome-ignore lint/a11y/useAnchorContent: This is intentional
              render={isExternal ? <a href={href} /> : <Link href={href} />}
            >
              <span className="font-heading in-data-highlighted:text-foreground text-muted-foreground">
                {item.label}
              </span>
              {item.upcoming && (
                <Badge
                  className="-me-0.5 font-medium opacity-0 group-hover:opacity-100"
                  size="sm"
                  variant="info"
                >
                  Upcoming
                </Badge>
              )}
            </MenuItem>
          );
        })}
      </MenuPopup>
    </Menu>
  );
}

// src/lib/shared-components/products-dropdown.svelte
<script lang="ts">
  import { DropdownMenu } from "bits-ui";
  import { ChevronDown } from "lucide-svelte";
  import { cn } from "../utils.js";
  import Badge from "../cossui-components/badge.svelte";
  import Button from "../cossui-components/button.svelte";
  import Menu from "../cossui-components/menu.svelte";
  import MenuPopup from "../cossui-components/menu-popup.svelte";

  interface ProductItem {
    href: string;
    label: string;
    upcoming?: boolean;
  }

  interface Props {
    items: ProductItem[];
  }

  let { items }: Props = $props();

  const gatewayOrigin: string = import.meta.env.VITE_COSS_URL ?? "";
  const uiGatewayOrigin: string = import.meta.env.VITE_COSS_UI_URL ?? "";

  function getLinkHref(item: ProductItem): { href: string; isExternal: boolean } {
    const isHomePage = item.href === "/";
    if (gatewayOrigin && !isHomePage) {
      return { href: `${gatewayOrigin}${item.href}`, isExternal: true };
    }
    if (uiGatewayOrigin && isHomePage) {
      return { href: uiGatewayOrigin, isExternal: true };
    }
    return { href: item.href, isExternal: false };
  }

  const menuItemClass =
    "[&>svg]:-mx-0.5 flex min-h-8 cursor-default select-none items-center gap-2 rounded-sm px-2 py-1 text-base text-foreground outline-none data-[disabled]:pointer-events-none data-[highlighted]:bg-accent data-[highlighted]:text-accent-foreground data-[disabled]:opacity-64 sm:min-h-7 sm:text-sm [&>svg:not([class*='opacity-'])]:opacity-80 [&>svg:not([class*='size-'])]:size-4.5 sm:[&>svg:not([class*='size-'])]:size-4 [&>svg]:pointer-events-none [&>svg]:shrink-0";
</script>

<Menu>
  <DropdownMenu.Trigger>
    {#snippet child({ props })}
      <Button {...props} variant="ghost">
        Products
        <ChevronDown class="size-4" />
      </Button>
    {/snippet}
  </DropdownMenu.Trigger>
  <MenuPopup align="center" sideOffset={4}>
    {#each items as item (item.href)}
      {@const { href, isExternal } = getLinkHref(item)}
      <DropdownMenu.Item>
        {#snippet child({ props })}
          <a
            {...props}
            {href}
            class={cn(menuItemClass, "group justify-between")}
            target={isExternal ? "_self" : undefined}
          >
            <span class="font-heading in-data-highlighted:text-foreground text-muted-foreground">
              {item.label}
            </span>
            {#if item.upcoming}
              <Badge
                class="-me-0.5 font-medium opacity-0 group-hover:opacity-100"
                size="sm"
                variant="info"
              >
                Upcoming
              </Badge>
            {/if}
          </a>
        {/snippet}
      </DropdownMenu.Item>
    {/each}
  </MenuPopup>
</Menu>
