// src/lib/components/shared-components/site-cta.svelte
<section>
  <div class="container flex w-full items-center justify-center gap-2 px-4 sm:px-6">
    <a
      class="relative inline-flex shrink-0 cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-lg border font-medium text-base outline-none transition-shadow not-disabled:inset-shadow-[0_1px_--theme(--color-white/16%)] border-primary bg-primary text-primary-foreground shadow-primary/24 shadow-xs hover:bg-primary/90 h-9 px-[calc(--spacing(3)-1px)] sm:h-8 sm:text-sm"
      href="https://i.cal.com/forms/0129f2a8-7b15-4850-b3fb-07944dfacb3c"
      rel="noreferrer"
      target="_blank"
    >
      Join the waitlist
    </a>
    <a
      class="relative inline-flex shrink-0 cursor-pointer items-center justify-center gap-2 whitespace-nowrap rounded-lg border font-medium text-base outline-none transition-shadow border-input bg-popover not-dark:bg-clip-padding text-foreground shadow-xs/5 hover:bg-accent/50 h-9 px-[calc(--spacing(3)-1px)] sm:h-8 sm:text-sm"
      href="https://cal.com/jobs"
    >
      Join the company
    </a>
  </div>
</section>

// src/lib/shared-components/site-cta.tsx
import { Button } from "@coss/ui/components/button";
import Link from "next/link";

export function SiteCta() {
  return (
    <section>
      <div className="container flex w-full items-center justify-center gap-2 px-4 sm:px-6">
        <Button
          render={
            // biome-ignore lint(a11y/useAnchorContent): knwon
            <a
              href="https://i.cal.com/forms/0129f2a8-7b15-4850-b3fb-07944dfacb3c"
              rel="noreferrer"
              target="_blank"
            />
          }
        >
          Join the waitlist
        </Button>
        <Button render={<Link href="https://cal.com/jobs" />} variant="outline">
          Join the company
        </Button>
      </div>
    </section>
  );
}
