// src/lib/components/shared-components/code-block.svelte
<script lang="ts">
import { ScrollArea } from '$lib/components/ui/scroll-area';
import CopyButton from './copy-button.svelte';
import LanguageIcon from './language-icon.svelte';

/**
 * Note: The original React component used `await highlightCode(code, language, { showLineNumbers })`
 * as an async Server Component. In Svelte/SvelteKit, code highlighting should be performed in a
 * +page.server.ts load function and the resulting HTML passed as the `highlightedCode` prop.
 */
interface Props {
  code: string;
  language: string;
  title?: string;
  copyButton?: boolean;
  showLineNumbers?: boolean;
  /** Pre-rendered highlighted HTML (e.g. from a server-side highlight function) */
  highlightedCode: string;
}

let {
  code,
  language,
  title,
  copyButton = true,
  showLineNumbers = true,
  highlightedCode
}: Props = $props();
</script>

<figure data-rehype-pretty-code-figure="">
  {#if title}
    <figcaption
      class="flex items-center gap-2 text-[.8125rem] text-code-foreground [&_svg]:size-4.5 [&_svg]:text-code-foreground sm:[&_svg]:size-4"
      data-language={language}
      data-rehype-pretty-code-title=""
    >
      <LanguageIcon {language} />
      {title}
    </figcaption>
  {/if}
  {#if copyButton}
    <CopyButton value={code} />
  {/if}
  <ScrollArea
    class="**:data-[slot=scroll-area-scrollbar]:data-[orientation=horizontal]:mx-2 **:data-[slot=scroll-area-scrollbar]:data-[orientation=vertical]:my-2"
  >
    <!-- svelte-ignore -->
    {@html highlightedCode}
  </ScrollArea>
</figure>

// src/lib/components/app/code-block.tsx
import { ScrollArea } from "@coss/ui/components/scroll-area";
import { highlightCode } from "@coss/ui/lib/highlight-code";
import { CopyButton } from "@coss/ui/shared/copy-button";
import { getIconForLanguageExtension } from "@coss/ui/shared/icons";

export async function CodeBlock({
  code,
  language,
  title,
  copyButton = true,
  showLineNumbers = true,
}: {
  code: string;
  language: string;
  title?: string | undefined;
  copyButton?: boolean;
  showLineNumbers?: boolean;
}) {
  const highlightedCode = await highlightCode(code, language, {
    showLineNumbers,
  });

  return (
    <figure data-rehype-pretty-code-figure="">
      {title && (
        <figcaption
          className="flex items-center gap-2 text-[.8125rem] text-code-foreground [&_svg]:size-4.5 [&_svg]:text-code-foreground sm:[&_svg]:size-4"
          data-language={language}
          data-rehype-pretty-code-title=""
        >
          {getIconForLanguageExtension(language)}
          {title}
        </figcaption>
      )}
      {copyButton && <CopyButton value={code} />}
      <ScrollArea className="**:data-[slot=scroll-area-scrollbar]:data-[orientation=horizontal]:mx-2 **:data-[slot=scroll-area-scrollbar]:data-[orientation=vertical]:my-2">
        <div dangerouslySetInnerHTML={{ __html: highlightedCode }} />
      </ScrollArea>
    </figure>
  );
}
