// src/lib/site-components/component-source.tsx
import fs from "node:fs/promises";
import path from "node:path";
import { CodeBlock } from "@coss/ui/shared/code-block";
import type * as React from "react";

import { CodeCollapsibleWrapper } from "@/components/code-collapsible-wrapper";
import { getRegistryItem } from "@/lib/registry";
import { cn } from "@/lib/utils";

export async function ComponentSource({
  name,
  src,
  title,
  language,
  collapsible = true,
  className,
}: React.ComponentProps<"div"> & {
  name?: string;
  src?: string;
  title?: string;
  language?: string;
  collapsible?: boolean;
}) {
  if (!name && !src) {
    return null;
  }

  let code: string | undefined;

  if (name) {
    const item = await getRegistryItem(name);
    code = item?.files?.[0]?.content;
  }

  if (src) {
    const file = await fs.readFile(path.join(process.cwd(), src), "utf-8");
    code = file;
  }

  if (!code) {
    return null;
  }

  const lang = language ?? title?.split(".").pop() ?? "tsx";

  if (!collapsible) {
    return (
      <div className={cn("relative", className)}>
        <CodeBlock code={code} language={lang} title={title} />
      </div>
    );
  }

  return (
    <CodeCollapsibleWrapper className={className}>
      <CodeBlock code={code} language={lang} title={title} />
    </CodeCollapsibleWrapper>
  );
}

// src/lib/components/app/component-source.svelte
<script lang="ts">
  import { browser } from "$app/environment";
  import type { HTMLAttributes } from "svelte/elements";
  import { cn } from "$lib/utils";
  import CodeBlock from "$lib/components/ui/code-block.svelte";
  import CodeCollapsibleWrapper from "$lib/components/app/code-collapsible-wrapper.svelte";
  // import { getRegistryItem } from "$lib/registry";

  let {
    name,
    src,
    title,
    language,
    collapsible = true,
    class: className,
  }: HTMLAttributes<HTMLDivElement> & {
    name?: string;
    src?: string;
    title?: string;
    language?: string;
    collapsible?: boolean;
  } = $props();

  async function loadCode(): Promise<string | undefined> {
    if (!name && !src) return undefined;

    if (name) {
      if (!browser) {
        const item = await getRegistryItem(name);
        return item?.files?.[0]?.content;
      }
      const resp = await fetch(`/api/registry/${encodeURIComponent(name)}`);
      if (!resp.ok) return undefined;
      const data = await resp.json();
      return data.content;
    }

    if (src) {
      if (!browser) {
        const { readFile } = await import("node:fs/promises");
        const { join } = await import("node:path");
        return readFile(join(process.cwd(), src), "utf-8");
      }
      const resp = await fetch(
        `/api/source-file?src=${encodeURIComponent(src)}`,
      );
      if (!resp.ok) return undefined;
      return resp.text();
    }
  }

  const codePromise = $derived(loadCode());
</script>

{#await codePromise then code}
  {#if code}
    {@const lang = language ?? title?.split(".").pop() ?? "svelte"}
    {#if !collapsible}
      <div class={cn("relative", className)}>
        <CodeBlock {code} language={lang} {title} />
      </div>
    {:else}
      <CodeCollapsibleWrapper class={className}>
        <CodeBlock {code} language={lang} {title} />
      </CodeCollapsibleWrapper>
    {/if}
  {/if}
{/await}
