// src/lib/components/app/component-preview.svelte
<script lang="ts">
  import type { HTMLAttributes } from "svelte/elements";
  import { cn } from "$lib/utils";
  import ComponentPreviewTabs from "$lib/components/app/component-preview-tabs.svelte";
  import ComponentSource from "$lib/components/app/component-source.svelte";
  import { Index } from "$lib/registry/__index__";

  let {
    name,
    class: className,
    align = "center",
    hideCode = false,
    ...restProps
  }: HTMLAttributes<HTMLDivElement> & {
    name: string;
    align?: "center" | "start" | "end";
    hideCode?: boolean;
  } = $props();

  const Component = $derived(Index[name]?.component);
  const metaClassName = $derived(Index[name]?.meta?.className);
</script>

{#if !Component}
  <p class="text-muted-foreground text-sm">
    Component
    <code
      class="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-[.8125rem]"
    >
      {name}
    </code>
    not found in registry.
  </p>
{:else}
  <ComponentPreviewTabs
    {align}
    class={cn(metaClassName, className)}
    {hideCode}
    {...restProps}
  >
    {#snippet component()}
      <svelte:component this={Component} />
    {/snippet}
    {#snippet source()}
      <ComponentSource collapsible={false} {name} />
    {/snippet}
  </ComponentPreviewTabs>
{/if}

// src/lib/components/app/component-preview.tsx
import { Index } from "@/registry/__index__";
import { ComponentPreviewTabs } from "@/components/component-preview-tabs";
import { ComponentSource } from "@/components/component-source";
import { cn } from "@/lib/utils";

interface ComponentPreviewProps
  extends Omit<React.ComponentProps<"div">, "ref"> {
  name: string;
  align?: "center" | "start" | "end";
  description?: string;
  hideCode?: boolean;
}

export function ComponentPreview({
  name,
  className,
  align = "center",
  hideCode = false,
  ...props
}: ComponentPreviewProps) {
  const Component = Index[name]?.component;
  const metaClassName = Index[name]?.meta?.className;

  if (!Component) {
    return (
      <p className="text-muted-foreground text-sm">
        Component{" "}
        <code className="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-[.8125rem]">
          {name}
        </code>{" "}
        not found in registry.
      </p>
    );
  }

  return (
    <ComponentPreviewTabs
      align={align}
      className={cn(metaClassName, className)}
      component={<Component />}
      hideCode={hideCode}
      source={<ComponentSource collapsible={false} name={name} />}
      {...props}
    />
  );
}
