// src/lib/components/app/docs/component-source.svelte
<script lang="ts">
  import CodeBlock from '#lib/components/app/code-block.svelte';
  import CodeCollapsibleWrapper from '#lib/components/app/code-collapsible-wrapper.svelte';
  import { cn } from '#lib/utils.js';
  import type { ComponentSourceFile } from '../../../../routes/api/component-source/[name]/+server';

  interface Props {
    class?: string;
    collapsible?: boolean;
    name: string;
    title?: string;
  }

  let { name, title, collapsible = true, class: className }: Props = $props();

  async function loadFiles(): Promise<ComponentSourceFile[] | undefined> {
    const resp = await fetch(`/api/component-source/${name}`);
    if (!resp.ok) return undefined;
    return (await resp.json()) as ComponentSourceFile[];
  }

  const filesPromise = $derived(loadFiles());
</script>

{#await filesPromise then files}
  {#if files}
    {#each files as file, i (file.filename)}
      {@const fileTitle = i === 0 ? (title ?? file.filename) : file.filename}
      {#if !collapsible}
        <div class={cn('relative', className)}>
          <CodeBlock code={file.raw} html={file.html} language="svelte" title={fileTitle} />
        </div>
      {:else}
        <CodeCollapsibleWrapper class={className}>
          <CodeBlock code={file.raw} html={file.html} language="svelte" title={fileTitle} />
        </CodeCollapsibleWrapper>
      {/if}
    {/each}
  {/if}
{/await}

// src/lib/components/app/component-source.tsx
import fs from "node:fs/promises";
import path from "node:path";
import { CodeBlock } from "@coss/ui/shared/code-block";
import type * as React from "react";
import { CodeCollapsibleWrapper } from "@/components/code-collapsible-wrapper";
import { getRegistryItem } from "@/lib/registry";
import { cn } from "@/lib/utils";

export async function ComponentSource({
  name,
  src,
  title,
  language,
  collapsible = true,
  className,
}: React.ComponentProps<"div"> & {
  name?: string;
  src?: string;
  title?: string;
  language?: string;
  collapsible?: boolean;
}) {
  if (!name && !src) {
    return null;
  }

  let code: string | undefined;

  if (name) {
    const item = await getRegistryItem(name);
    code = item?.files?.[0]?.content;
  }

  if (src) {
    const file = await fs.readFile(path.join(process.cwd(), src), "utf-8");
    code = file;
  }

  if (!code) {
    return null;
  }

  const lang = language ?? title?.split(".").pop() ?? "tsx";

  if (!collapsible) {
    return (
      <div className={cn("relative", className)}>
        <CodeBlock code={code} language={lang} title={title} />
      </div>
    );
  }

  return (
    <CodeCollapsibleWrapper className={className}>
      <CodeBlock code={code} language={lang} title={title} />
    </CodeCollapsibleWrapper>
  );
}
