// src/lib/site-components/component-preview.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { cn } from "../utils.js";
  import ComponentPreviewTabs from "./component-preview-tabs.svelte";

  /**
   * In SvelteKit the component registry lookup happens in the server load
   * function. Pass the resolved component and source snippets as props.
   */
  interface Props {
    name?: string;
    class?: string;
    metaClassName?: string;
    align?: "center" | "start" | "end";
    hideCode?: boolean;
    component?: Snippet;
    source?: Snippet;
  }

  let {
    name,
    class: className,
    metaClassName,
    align = "center",
    hideCode = false,
    component,
    source,
  }: Props = $props();
</script>

{#if component && source}
  <ComponentPreviewTabs
    {align}
    class={cn(metaClassName, className)}
    {component}
    {hideCode}
    {source}
  />
{:else}
  <p class="text-muted-foreground text-sm">
    Component
    <code class="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-[.8125rem]">
      {name}
    </code>
    not found in registry.
  </p>
{/if}

// src/lib/components/app/component-preview.tsx
import { Index } from "@/registry/__index__";
import { ComponentPreviewTabs } from "@/components/component-preview-tabs";
import { ComponentSource } from "@/components/component-source";
import { cn } from "@/lib/utils";

interface ComponentPreviewProps
  extends Omit<React.ComponentProps<"div">, "ref"> {
  name: string;
  align?: "center" | "start" | "end";
  description?: string;
  hideCode?: boolean;
}

export function ComponentPreview({
  name,
  className,
  align = "center",
  hideCode = false,
  ...props
}: ComponentPreviewProps) {
  const Component = Index[name]?.component;
  const metaClassName = Index[name]?.meta?.className;

  if (!Component) {
    return (
      <p className="text-muted-foreground text-sm">
        Component{" "}
        <code className="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-[.8125rem]">
          {name}
        </code>{" "}
        not found in registry.
      </p>
    );
  }

  return (
    <ComponentPreviewTabs
      align={align}
      className={cn(metaClassName, className)}
      component={<Component />}
      hideCode={hideCode}
      source={<ComponentSource collapsible={false} name={name} />}
      {...props}
    />
  );
}
