// src/routes/demos/drawer/page.tsx
import { Button } from "$lib/components/ui/button";
import {
  Drawer,
  DrawerHeader,
  DrawerPanel,
  DrawerPopup,
  DrawerTitle,
  DrawerTrigger,
} from "$lib/components/ui/drawer";

export default function Particle() {
  return (
    <div className="flex flex-wrap gap-2">
      <Drawer position="right">
        <DrawerTrigger render={<Button variant="outline" />}>
          Right
        </DrawerTrigger>
        <DrawerPopup variant="inset">
          <DrawerHeader>
            <DrawerTitle>Right</DrawerTitle>
          </DrawerHeader>
          <DrawerPanel>
            <p className="text-muted-foreground text-sm">
              Content from the right.
            </p>
          </DrawerPanel>
        </DrawerPopup>
      </Drawer>
      <Drawer position="left">
        <DrawerTrigger render={<Button variant="outline" />}>
          Left
        </DrawerTrigger>
        <DrawerPopup variant="inset">
          <DrawerHeader>
            <DrawerTitle>Left</DrawerTitle>
          </DrawerHeader>
          <DrawerPanel>
            <p className="text-muted-foreground text-sm">
              Content from the left.
            </p>
          </DrawerPanel>
        </DrawerPopup>
      </Drawer>
      <Drawer position="top">
        <DrawerTrigger render={<Button variant="outline" />}>Top</DrawerTrigger>
        <DrawerPopup variant="inset">
          <DrawerHeader>
            <DrawerTitle>Top</DrawerTitle>
          </DrawerHeader>
          <DrawerPanel>
            <p className="text-muted-foreground text-sm">
              Content from the top.
            </p>
          </DrawerPanel>
        </DrawerPopup>
      </Drawer>
      <Drawer>
        <DrawerTrigger render={<Button variant="outline" />}>
          Bottom
        </DrawerTrigger>
        <DrawerPopup variant="inset">
          <DrawerHeader>
            <DrawerTitle>Bottom</DrawerTitle>
          </DrawerHeader>
          <DrawerPanel>
            <p className="text-muted-foreground text-sm">
              Content from the bottom.
            </p>
          </DrawerPanel>
        </DrawerPopup>
      </Drawer>
    </div>
  );
}

// src/routes/demos/drawer/+page.svelte
<script lang="ts">
    import ComponentPreviewTabs from "$lib/components/app/ComponentPreviewTabs.svelte";
    import { Button } from "$lib/components/ui/button";
    import {
        Drawer,
        DrawerHeader,
        DrawerPanel,
        DrawerPopup,
        DrawerTitle,
        DrawerTrigger,
    } from "$lib/components/ui/drawer";
</script>

<ComponentPreviewTabs>
    <div class="flex flex-wrap gap-2">
        <Drawer position="right">
            <DrawerTrigger>
                <Button variant="outline">Right</Button>
            </DrawerTrigger>
            <DrawerPopup variant="inset">
                <DrawerHeader>
                    <DrawerTitle>Right</DrawerTitle>
                </DrawerHeader>
                <DrawerPanel>
                    <p class="text-muted-foreground text-sm">
                        Content from the right.
                    </p>
                </DrawerPanel>
            </DrawerPopup>
        </Drawer>

        <Drawer position="left">
            <DrawerTrigger>
                <Button variant="outline">Left</Button>
            </DrawerTrigger>
            <DrawerPopup variant="inset">
                <DrawerHeader>
                    <DrawerTitle>Left</DrawerTitle>
                </DrawerHeader>
                <DrawerPanel>
                    <p class="text-muted-foreground text-sm">
                        Content from the left.
                    </p>
                </DrawerPanel>
            </DrawerPopup>
        </Drawer>

        <Drawer position="top">
            <DrawerTrigger>
                <Button variant="outline">Top</Button>
            </DrawerTrigger>
            <DrawerPopup variant="inset">
                <DrawerHeader>
                    <DrawerTitle>Top</DrawerTitle>
                </DrawerHeader>
                <DrawerPanel>
                    <p class="text-muted-foreground text-sm">
                        Content from the top.
                    </p>
                </DrawerPanel>
            </DrawerPopup>
        </Drawer>

        <Drawer>
            <DrawerTrigger>
                <Button variant="outline">Bottom</Button>
            </DrawerTrigger>
            <DrawerPopup variant="inset">
                <DrawerHeader>
                    <DrawerTitle>Bottom</DrawerTitle>
                </DrawerHeader>
                <DrawerPanel>
                    <p class="text-muted-foreground text-sm">
                        Content from the bottom.
                    </p>
                </DrawerPanel>
            </DrawerPopup>
        </Drawer>
    </div>
</ComponentPreviewTabs>
