// src/lib/components/ui/checkbox-group/done/coss.old/checkbox-group.tsx
"use client";

import { CheckboxGroup as CheckboxGroupPrimitive } from "@base-ui/react/checkbox-group";
import { cn } from "@coss/ui/lib/utils";

function CheckboxGroup({ className, ...props }: CheckboxGroupPrimitive.Props) {
  return (
    <CheckboxGroupPrimitive
      className={cn("flex flex-col items-start gap-3", className)}
      {...props}
    />
  );
}

export { CheckboxGroup, CheckboxGroupPrimitive };

// src/lib/cossui-components/checkbox/checkbox-group.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import { cn } from "$lib/utils.js";

  interface Props extends HTMLAttributes<HTMLDivElement> {
    children?: Snippet;
    value?: string[];
    onValueChange?: (value: string[]) => void;
  }

  let {
    class: className,
    children,
    value = $bindable([]),
    onValueChange,
    ...restProps
  }: Props = $props();
</script>

<div
  class={cn("flex flex-col items-start gap-3", className)}
  data-slot="checkbox-group"
  {...restProps}
>
  {@render children?.()}
</div>
