// src/lib/site-components/site-footer.tsx
import Link from "next/link";

export function SiteFooter() {
  return (
    <footer className="flex flex-col gap-0.5">
      <p>
        <Link className="font-heading font-semibold text-lg" href="/">
          coss.com <span className="text-muted-foreground/72">ui</span>
        </Link>
      </p>
      <p className="text-muted-foreground text-sm">
        Built by and for the team of{" "}
        <a
          className="font-medium underline-offset-4 hover:underline"
          href="https://cal.com"
          rel="noopener noreferrer"
          target="_blank"
        >
          Cal.com
        </a>
        , Inc. — the leading commercial open source company
        (&ldquo;coss&rdquo;).
      </p>
    </footer>
  );
}

// src/lib/app-components/site-footer.svelte
<footer class="flex flex-col gap-0.5">
  <p>
    <a class="font-heading font-semibold text-lg" href="/">
      coss.com <span class="text-muted-foreground/72">ui</span>
    </a>
  </p>
  <p class="text-muted-foreground text-sm">
    Built by and for the team of
    <a
      class="font-medium underline-offset-4 hover:underline"
      href="https://cal.com"
      rel="noopener noreferrer"
      target="_blank"
    >Cal.com</a>, Inc. — the leading commercial open source company ("coss").
  </p>
</footer>
