// src/lib/components/app/component-preview.tsx
import { Index } from "@/registry/__index__";
import { ComponentPreviewTabs } from "@/components/component-preview-tabs";
import { ComponentSource } from "@/components/component-source";
import { cn } from "@/lib/utils";

interface ComponentPreviewProps
  extends Omit<React.ComponentProps<"div">, "ref"> {
  name: string;
  align?: "center" | "start" | "end";
  description?: string;
  hideCode?: boolean;
}

export function ComponentPreview({
  name,
  className,
  align = "center",
  hideCode = false,
  ...props
}: ComponentPreviewProps) {
  const Component = Index[name]?.component;
  const metaClassName = Index[name]?.meta?.className;

  if (!Component) {
    return (
      <p className="text-muted-foreground text-sm">
        Component{" "}
        <code className="relative rounded bg-muted px-[0.3rem] py-[0.2rem] font-mono text-[.8125rem]">
          {name}
        </code>{" "}
        not found in registry.
      </p>
    );
  }

  return (
    <ComponentPreviewTabs
      align={align}
      className={cn(metaClassName, className)}
      component={<Component />}
      hideCode={hideCode}
      source={<ComponentSource collapsible={false} name={name} />}
      {...props}
    />
  );
}

// src/lib/components/app/docs/component-preview.svelte
<script lang="ts">
  import ParticleSource from '#lib/components/app/particle-source.svelte';
  import { Spinner } from '#lib/components/ui/spinner/index.js';
  import { Tabs, TabsList, TabsPanel, TabsTab } from '#lib/components/ui/tabs/index.js';
  import { allParticles } from '#lib/registry/registry-particles.js';
  import { cn } from '#lib/utils.js';

  interface Props {
    align?: 'center' | 'start';
    class?: string;
    name: string;
  }

  let { name, align = 'center', class: className }: Props = $props();

  const particle = $derived(allParticles[name]);
</script>

{#if particle}
  <Tabs class={cn('mt-6', className)} value="preview">
    <TabsList>
      <TabsTab value="preview">Preview</TabsTab>
      <TabsTab value="code">Code</TabsTab>
    </TabsList>
    <TabsPanel value="preview">
      <div
        class={cn(
          'flex min-h-56 items-center rounded-xl border p-8',
          align === 'start' ? 'justify-start' : 'justify-center'
        )}
      >
        {#await particle.component()}
          <Spinner />
        {:then { default: Comp }}
          <Comp />
        {/await}
      </div>
    </TabsPanel>
    <TabsPanel value="code">
      <ParticleSource name={particle.file} />
    </TabsPanel>
  </Tabs>
{/if}
