// src/lib/components/ui/checkbox-group/done/coss.old/checkbox-group.tsx
"use client";

import { CheckboxGroup as CheckboxGroupPrimitive } from "@base-ui/react/checkbox-group";
import { cn } from "@coss/ui/lib/utils";

function CheckboxGroup({ className, ...props }: CheckboxGroupPrimitive.Props) {
  return (
    <CheckboxGroupPrimitive
      className={cn("flex flex-col items-start gap-3", className)}
      {...props}
    />
  );
}

export { CheckboxGroup, CheckboxGroupPrimitive };

// src/lib/components/ui/checkbox-group/checkbox-group.svelte
<script lang="ts">
  import { CheckboxGroup as CheckboxGroupPrimitive } from '@shardsui/svelte/checkbox-group';
  import type { ComponentProps } from 'svelte';
  import { cn } from '#lib/utils.js';

  let {
    ref = $bindable(null),
    value = $bindable([]),
    class: className,
    ...restProps
  }: ComponentProps<typeof CheckboxGroupPrimitive> = $props();
</script>

<CheckboxGroupPrimitive
  bind:ref
  bind:value
  class={cn('flex flex-col items-start gap-3', className)}
  {...restProps}
/>
