// src/lib/components/app/command-menu.svelte
<script lang="ts">
  import { cn } from "$lib/utils";
  import {
    Dialog,
    DialogContent,
    DialogOverlay,
    DialogPortal,
    DialogTrigger,
  } from "$lib/components/ui/dialog";
  import Search from "@lucide/svelte/icons/search";
  import CornerDownLeft from "@lucide/svelte/icons/corner-down-left";
  import Atom from "@lucide/svelte/icons/atom";
  import BookOpen from "@lucide/svelte/icons/book-open";
  import { buttonVariants } from "$lib/components/ui/button";
  import { Kbd, KbdGroup } from "$lib/components/ui/kbd";
  import { useIsMac } from "$lib/hooks/use-is-mac.svelte";

  interface PageItem {
    value: string;
    label: string;
    url: string;
    isComponent: boolean;
    keywords?: string[];
  }

  interface PageGroup {
    value: string;
    items: PageItem[];
  }

  interface PageNode {
    type: "page";
    name: string | unknown;
    url: string;
  }

  interface FolderNode {
    type: "folder";
    name: string | unknown;
    children: (PageNode | FolderNode)[];
  }

  interface NavTree {
    children: (PageNode | FolderNode)[];
  }

  interface Props {
    tree?: NavTree;
    navItems?: { href: string; label: string }[];
    packageManager?: "pnpm" | "npm" | "yarn" | "bun";
  }

  let { tree, navItems, packageManager = "pnpm" }: Props = $props();

  let open = $state(false);
  let query = $state("");
  let selectedType = $state<"page" | "component" | null>(null);
  let copyPayload = $state("");

  // Detect macOS
  let isMac = useIsMac();

  // Build grouped items from tree
  const groupedItems = $derived<PageGroup[]>(
    (() => {
      const groups: PageGroup[] = [];

      if (navItems && navItems.length > 0) {
        groups.push({
          items: navItems.map((item) => ({
            isComponent: false,
            keywords: ["nav", "navigation", item.label.toLowerCase()],
            label: item.label,
            url: item.href,
            value: `Navigation ${item.label}`,
          })),
          value: "Pages",
        });
      }

      if (tree) {
        tree.children.forEach((group) => {
          if (group.type === "folder") {
            const items: PageItem[] = [];
            group.children.forEach((item) => {
              if (item.type === "page") {
                const isComponent = item.url.includes("/components/");
                const itemName = String(item.name ?? "");
                items.push({
                  isComponent,
                  keywords: isComponent ? ["component"] : undefined,
                  label: itemName,
                  url: item.url,
                  value: itemName ? `${String(group.name)} ${itemName}` : "",
                });
              }
            });
            if (items.length > 0) {
              groups.push({ items, value: String(group.name) });
            }
          }
        });
      }

      return groups;
    })(),
  );

  // Filter items based on search query
  const filteredGroups = $derived<PageGroup[]>(
    (() => {
      if (!query.trim()) return groupedItems;
      const q = query.toLowerCase();
      return groupedItems
        .map((group) => ({
          ...group,
          items: group.items.filter(
            (item) =>
              item.label.toLowerCase().includes(q) ||
              item.keywords?.some((k) => k.includes(q)),
          ),
        }))
        .filter((group) => group.items.length > 0);
    })(),
  );

  function handleItemHighlight(item: PageItem) {
    if (item.isComponent) {
      const componentName = item.url.split("/").pop();
      selectedType = "component";
      const registryItem = `@coss/${componentName}`;
      let cmd: string;
      switch (packageManager) {
        case "pnpm":
          cmd = `pnpm dlx shadcn@latest add ${registryItem}`;
          break;
        case "bun":
          cmd = `bunx --bun shadcn@latest add ${registryItem}`;
          break;
        case "yarn":
          cmd = `yarn dlx shadcn@latest add ${registryItem}`;
          break;
        default:
          cmd = `npx shadcn@latest add ${registryItem}`;
      }
      copyPayload = cmd;
    } else {
      selectedType = "page";
      copyPayload = "";
    }
  }

  async function copyPayloadToClipboard() {
    if (copyPayload) {
      try {
        await navigator.clipboard.writeText(copyPayload);
      } catch (err) {
        console.error("Failed to copy:", err);
      }
    }
  }

  $effect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if ((e.key === "k" && (e.metaKey || e.ctrlKey)) || e.key === "/") {
        if (
          (e.target instanceof HTMLElement && e.target.isContentEditable) ||
          e.target instanceof HTMLInputElement ||
          e.target instanceof HTMLTextAreaElement ||
          e.target instanceof HTMLSelectElement
        ) {
          return;
        }
        e.preventDefault();
        open = !open;
      }

      if (e.key === "c" && (e.metaKey || e.ctrlKey) && open) {
        if (selectedType === "page" || selectedType === "component") {
          copyPayloadToClipboard();
        }
      }
    }

    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  });
</script>

<!-- Trigger button -->
<Dialog bind:open>
  <DialogTrigger>
    {#snippet child({ props })}
      <button
        {...props}
        class={cn(
          buttonVariants({ variant: "outline" }),
          "gap-2 text-muted-foreground",
        )}
        type="button"
      >
        <Search class="size-4" strokeWidth={2} />
        <span class="hidden sm:inline">Search documentation…</span>
        <KbdGroup class="gap-1">
          <Kbd>{isMac.cmdOrCtrl}</Kbd>
          <Kbd class="aspect-square">K</Kbd>
        </KbdGroup>
      </button>
    {/snippet}
  </DialogTrigger>

  <DialogPortal>
    <DialogOverlay
      class="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm data-[state=closed]:animate-out data-[state=open]:animate-in data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0"
    />
    <DialogContent
      class="fixed top-[10%] left-1/2 z-50 w-full max-w-lg -translate-x-1/2 overflow-hidden rounded-2xl border bg-popover shadow-xl data-[state=closed]:animate-out data-[state=open]:animate-in data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95"
    >
      <!-- Search input -->
      <div class="flex items-center gap-2 border-b px-4 py-3">
        <Search class="size-4 shrink-0 text-muted-foreground" strokeWidth={2} />
        <input
          autofocus
          bind:value={query}
          class="flex-1 bg-transparent text-sm outline-none placeholder:text-muted-foreground"
          placeholder="Search documentation…"
          type="text"
        />
      </div>

      <!-- Results -->
      <div class="max-h-[60vh] overflow-y-auto p-2">
        {#if filteredGroups.length === 0}
          <div class="px-4 py-8 text-center text-muted-foreground text-sm">
            No results found.
          </div>
        {:else}
          {#each filteredGroups as group (group.value)}
            <div class="mb-2">
              <div
                class="px-2 py-1.5 text-muted-foreground text-xs font-medium"
              >
                {group.value}
              </div>
              {#each group.items as item (item.value)}
                <a
                  class="flex w-full items-center gap-2 rounded-md px-2 py-2 text-sm transition-colors hover:bg-accent focus:bg-accent focus:outline-none"
                  href={item.url}
                  onclick={() => {
                    open = false;
                  }}
                  onmouseenter={() => handleItemHighlight(item)}
                  onfocus={() => handleItemHighlight(item)}
                >
                  {#if item.isComponent}
                    <Atom class="size-4 opacity-80" strokeWidth={2} />
                  {:else}
                    <BookOpen class="size-4 opacity-80" strokeWidth={2} />
                  {/if}
                  <span class="flex-1">{item.label}</span>
                </a>
              {/each}
            </div>
          {/each}
        {/if}
      </div>

      <!-- Footer -->
      <div
        class="flex items-center justify-between border-t px-4 py-2 text-muted-foreground text-xs"
      >
        <div class="flex items-center gap-2">
          <span class="whitespace-nowrap">Go to Page</span>
          <Kbd>
            <CornerDownLeft class="size-3" strokeWidth={2} />
          </Kbd>
        </div>
        {#if copyPayload}
          <div class="flex min-w-0 items-center gap-2">
            <span class="truncate font-mono">{copyPayload}</span>
            <KbdGroup>
              <Kbd>{isMac.cmdOrCtrl}</Kbd>
              <Kbd>C</Kbd>
            </KbdGroup>
          </div>
        {/if}
      </div>
    </DialogContent>
  </DialogPortal>
</Dialog>

// src/lib/site-components/command-menu.tsx
"use client";

import { CommandPanel } from "@coss/ui/components/command";
import {
  ArrowTurnBackwardIcon,
  Atom01Icon,
  BookOpen02Icon,
  Search01Icon,
} from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import Link from "next/link";
import type { ComponentProps } from "react";
import * as React from "react";
import { useConfig } from "@/hooks/use-config";
import { useIsMac } from "@/hooks/use-is-mac";
import type { source } from "@/lib/source";
import { useCopyToClipboard } from "@/registry/default/hooks/use-copy-to-clipboard";
import { Button } from "@/registry/default/ui/button";
import {
  Command,
  CommandCollection,
  CommandDialog,
  CommandDialogPopup,
  CommandDialogTrigger,
  CommandEmpty,
  CommandFooter,
  CommandGroup,
  CommandGroupLabel,
  CommandInput,
  CommandItem,
  CommandList,
} from "@/registry/default/ui/command";
import { Kbd, KbdGroup } from "@/registry/default/ui/kbd";

interface PageItem {
  value: string;
  label: string;
  url: string;
  isComponent: boolean;
  keywords?: string[];
}

interface PageGroup {
  value: string;
  items: PageItem[];
}

export function CommandMenu({
  tree,
  navItems,
  ...props
}: ComponentProps<typeof CommandDialog> & {
  tree: typeof source.pageTree;
  navItems?: { href: string; label: string }[];
}) {
  const isMac = useIsMac();
  const [config] = useConfig();
  const { copyToClipboard } = useCopyToClipboard();
  const [open, setOpen] = React.useState(false);
  const [selectedType, setSelectedType] = React.useState<
    "page" | "component" | null
  >(null);
  const [copyPayload, setCopyPayload] = React.useState("");
  const packageManager = config.packageManager || "pnpm";

  // Convert tree structure to grouped items
  const groupedItems = React.useMemo<PageGroup[]>(() => {
    const groups: PageGroup[] = [];

    // Add nav items group
    if (navItems && navItems.length > 0) {
      groups.push({
        items: navItems.map((item) => ({
          isComponent: false,
          keywords: ["nav", "navigation", item.label.toLowerCase()],
          label: item.label,
          url: item.href,
          value: `Navigation ${item.label}`,
        })),
        value: "Pages",
      });
    }

    // Add tree groups
    tree.children.forEach((group) => {
      if (group.type === "folder") {
        const items: PageItem[] = [];
        group.children.forEach((item) => {
          if (item.type === "page") {
            const isComponent = item.url.includes("/components/");
            const itemName = item.name?.toString() || "";
            items.push({
              isComponent,
              keywords: isComponent ? ["component"] : undefined,
              label: itemName,
              url: item.url,
              value: itemName ? `${group.name} ${itemName}` : "",
            });
          }
        });
        if (items.length > 0) {
          groups.push({
            items,
            value:
              typeof group.name === "string" ? group.name : String(group.name),
          });
        }
      }
    });

    return groups;
  }, [tree, navItems]);

  const handlePageHighlight = React.useCallback(
    (item: PageItem) => {
      if (item.isComponent) {
        const componentName = item.url.split("/").pop();
        setSelectedType("component");
        const registryItem = `@coss/${componentName}`;
        let cmd: string;
        switch (packageManager) {
          case "pnpm":
            cmd = `pnpm dlx shadcn@latest add ${registryItem}`;
            break;
          case "bun":
            cmd = `bunx --bun shadcn@latest add ${registryItem}`;
            break;
          case "yarn":
            cmd = `yarn dlx shadcn@latest add ${registryItem}`;
            break;
          default:
            cmd = `npx shadcn@latest add ${registryItem}`;
        }

        setCopyPayload(cmd);
      } else {
        setSelectedType("page");
        setCopyPayload("");
      }
    },
    [packageManager],
  );

  React.useEffect(() => {
    const down = (e: KeyboardEvent) => {
      if ((e.key === "k" && (e.metaKey || e.ctrlKey)) || e.key === "/") {
        if (
          (e.target instanceof HTMLElement && e.target.isContentEditable) ||
          e.target instanceof HTMLInputElement ||
          e.target instanceof HTMLTextAreaElement ||
          e.target instanceof HTMLSelectElement
        ) {
          return;
        }

        e.preventDefault();
        setOpen((open) => !open);
      }

      if (e.key === "c" && (e.metaKey || e.ctrlKey)) {
        if (selectedType === "page" || selectedType === "component") {
          copyToClipboard(copyPayload);
        }
      }
    };

    document.addEventListener("keydown", down);
    return () => document.removeEventListener("keydown", down);
  }, [copyPayload, selectedType, copyToClipboard]);

  return (
    <CommandDialog onOpenChange={setOpen} open={open} {...props}>
      <CommandDialogTrigger render={<Button variant="outline" />}>
        <HugeiconsIcon icon={Search01Icon} strokeWidth={2} />
        <KbdGroup className="gap-1">
          <Kbd>{isMac ? "⌘" : "Ctrl"}</Kbd>
          <Kbd className="aspect-square">K</Kbd>
        </KbdGroup>
      </CommandDialogTrigger>
      <CommandDialogPopup>
        <Command
          items={groupedItems}
          onItemHighlighted={(highlightedValue) => {
            const item = highlightedValue as PageItem | null;
            if (item) {
              handlePageHighlight(item);
            }
          }}
        >
          <CommandInput placeholder="Search documentation…" />
          <CommandPanel>
            <CommandEmpty>No results found.</CommandEmpty>
            <CommandList>
              {(group: PageGroup, _index: number) => (
                <CommandGroup items={group.items} key={group.value}>
                  <CommandGroupLabel>{group.value}</CommandGroupLabel>
                  <CommandCollection>
                    {(item: PageItem) => (
                      <CommandItem
                        className="flex w-full items-center"
                        key={item.value}
                        render={
                          <Link
                            href={item.url}
                            onNavigate={() => setOpen(false)}
                          />
                        }
                      >
                        <HugeiconsIcon
                          className="mr-2 h-4 w-4 opacity-80"
                          icon={item.isComponent ? Atom01Icon : BookOpen02Icon}
                          strokeWidth={2}
                        />
                        <span className="flex-1">{item.label}</span>
                      </CommandItem>
                    )}
                  </CommandCollection>
                </CommandGroup>
              )}
            </CommandList>
          </CommandPanel>
          <CommandFooter>
            <div className="flex items-center gap-2">
              <span className="whitespace-nowrap">Go to Page</span>
              <Kbd>
                <HugeiconsIcon icon={ArrowTurnBackwardIcon} strokeWidth={2} />
              </Kbd>
            </div>
            {copyPayload && (
              <div className="flex min-w-0 items-center gap-2">
                <span className="truncate font-mono">{copyPayload}</span>
                <KbdGroup>
                  <Kbd>{isMac ? "⌘" : "Ctrl"}</Kbd>
                  <Kbd>C</Kbd>
                </KbdGroup>
              </div>
            )}
          </CommandFooter>
        </Command>
      </CommandDialogPopup>
    </CommandDialog>
  );
}
