// src/lib/components/app/component-source.tsx
import fs from "node:fs/promises";
import path from "node:path";
import { CodeBlock } from "@coss/ui/shared/code-block";
import type * as React from "react";
import { CodeCollapsibleWrapper } from "@/components/code-collapsible-wrapper";
import { getRegistryItem } from "@/lib/registry";
import { cn } from "@/lib/utils";

export async function ComponentSource({
  name,
  src,
  title,
  language,
  collapsible = true,
  className,
}: React.ComponentProps<"div"> & {
  name?: string;
  src?: string;
  title?: string;
  language?: string;
  collapsible?: boolean;
}) {
  if (!name && !src) {
    return null;
  }

  let code: string | undefined;

  if (name) {
    const item = await getRegistryItem(name);
    code = item?.files?.[0]?.content;
  }

  if (src) {
    const file = await fs.readFile(path.join(process.cwd(), src), "utf-8");
    code = file;
  }

  if (!code) {
    return null;
  }

  const lang = language ?? title?.split(".").pop() ?? "tsx";

  if (!collapsible) {
    return (
      <div className={cn("relative", className)}>
        <CodeBlock code={code} language={lang} title={title} />
      </div>
    );
  }

  return (
    <CodeCollapsibleWrapper className={className}>
      <CodeBlock code={code} language={lang} title={title} />
    </CodeCollapsibleWrapper>
  );
}

// src/lib/site-components/component-source.svelte
<script lang="ts">
  import { cn } from "../utils.js";
  import CodeBlock from "../shared-components/code-block.svelte";
  import CodeCollapsibleWrapper from "./code-collapsible-wrapper.svelte";

  /**
   * In SvelteKit, server-side file reading happens in a load function.
   * Pass the already-loaded `code` string and `highlightedCode` HTML here.
   */
  interface Props {
    class?: string;
    code?: string;
    title?: string;
    language?: string;
    collapsible?: boolean;
    /** Pre-rendered highlighted HTML from a server-side highlight function */
    highlightedCode?: string;
  }

  let {
    class: className,
    code,
    title,
    language,
    collapsible = true,
    highlightedCode = "",
  }: Props = $props();

  const lang = $derived(language ?? title?.split(".").pop() ?? "tsx");
</script>

{#if code}
  {#if !collapsible}
    <div class={cn("relative", className)}>
      <CodeBlock {code} language={lang} {title} {highlightedCode} />
    </div>
  {:else}
    <CodeCollapsibleWrapper class={className}>
      <CodeBlock {code} language={lang} {title} {highlightedCode} />
    </CodeCollapsibleWrapper>
  {/if}
{/if}
